[streamfwd]
port = 8889
ipAddr = 0.0.0.0

httpEventCollectorToken = e374cb03-2f02-4cba-b0ce-b97652b0dae0

indexer.0.uri = https://localhost:8088

netflowReceiver.0.ip = 198.18.134.22
netflowReceiver.0.port = 9996
netflowReceiver.0.decoder = netflow
